### ISSUE TITLE
U followed by U2 in -DAX

### ISSUE THREAD

**Issue by nulaft** [efrantar/rob-twophase#8]
I have compiled rob-twophase using the -DAX flag.
If I run ./twophase -t 8 -n 20 and let it solve this cube:
solve RFLDUFLDURRBBRDURRULFBFLDUBLFLLDUBDDDRFBLUUUFDLFBBRBFR
One of the solutions found is:
(U D') F' L' D' (F B2) (R L2) (U D) (F' B2) **U U2** F' R2 D2 F L2 B' (16)
which has a U move followed by a U2 move!

Is this a bug or does the algorithm allow adjacent moves to be on the same face?

**Comment by nulaft** [comment]
For the same cube and settings I also get this solution:
(R L) B' (U2 D2) R (U' D2) F2 U' (R' L2) **U' D2** (F' B2) D2 R2 D2 R2 B (16)
Where a U' move is followed by a D2 move. I think in -DAX mode this should only be allowed as a compound move (U' D2).

**Comment by efrantar** [comment]
Well spotted!

This can happen because there are no move restrictions during the phase 1 and phase 2 transition. The reason is that we cannot use the `move::next[m]` mask because it imposes an ordering on commutative moves (for example R must always come before L in HTM). In unlucky cases if a phase 1 solution ends in say L but the corresponding shortest phase 2 solution must start with R2, then this overall solution will only be found during the next search with higher phase 1 depth. On average, this leads to a ~10% slow-down (in solving time not in average solution length, the latter probably hardly increases when searching for more than 1-2 milliseconds), which is why we don't do it.

It could of course be addressed with a different bitmask, but properly generating those for all 8 solving modes is a bit messy (and for `-DQT` metrics you would probably also need to mess around with a `move::qt_skip` alternative), which is why I didn't bother to do it. Especially since this issue is only really evident sometimes when returning many solutions and hardly affects performance otherwise.

If you are only interested in solving with `-DAX` then you could try to simply replace `move::p2mask` in the following line with `move::p2mask & move::next[moves[depth - 1]]`.

https://github.com/efrantar/rob-twophase/blob/70db5f9a065e4d1c47a41b57fb86eb78a7847923/src/solve.cpp#L84

This should not only fully resolve your issue but it should also be completely safe as the only commutative moves in axial mode are half-slice turns, which are however always phase 2 moves and hence the situation I outlined above cannot occur.

**Comment by efrantar** [comment]
Upon further reflection, the additional bitmask turned out to be quite a bit easier to add than I initially anticipated. Thus the issue should now be fixed entirely with 23f3098d0f45949bd1b68959fdc16e0d2317f8b5 (if you run into a similar situation again please let me know, that is indeed a bug then). 

Thank you for bringing this to my attention.
